// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcU5pO5PkxJm4YARHPi_qACj153BMNlmI',
    appId: '1:375745979677:web:7231ff82bc1c6a8a52adf4',
    messagingSenderId: '375745979677',
    projectId: 'webrtc-dd37f',
    authDomain: 'webrtc-dd37f.firebaseapp.com',
    storageBucket: 'webrtc-dd37f.firebasestorage.app',
    measurementId: 'G-67HECVS9Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC31f3mk6gO9L7IbbsI9UknazrhAFWPLto',
    appId: '1:375745979677:android:72eb2dc95f25499952adf4',
    messagingSenderId: '375745979677',
    projectId: 'webrtc-dd37f',
    storageBucket: 'webrtc-dd37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FiicK1OMN67lXnkYfPndQOLWs3pwIX0',
    appId: '1:375745979677:ios:598ea634810043d052adf4',
    messagingSenderId: '375745979677',
    projectId: 'webrtc-dd37f',
    storageBucket: 'webrtc-dd37f.firebasestorage.app',
    iosBundleId: 'com.example.webrtcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FiicK1OMN67lXnkYfPndQOLWs3pwIX0',
    appId: '1:375745979677:ios:598ea634810043d052adf4',
    messagingSenderId: '375745979677',
    projectId: 'webrtc-dd37f',
    storageBucket: 'webrtc-dd37f.firebasestorage.app',
    iosBundleId: 'com.example.webrtcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcU5pO5PkxJm4YARHPi_qACj153BMNlmI',
    appId: '1:375745979677:web:36df1551a456ca5252adf4',
    messagingSenderId: '375745979677',
    projectId: 'webrtc-dd37f',
    authDomain: 'webrtc-dd37f.firebaseapp.com',
    storageBucket: 'webrtc-dd37f.firebasestorage.app',
    measurementId: 'G-H2EB2WGYPZ',
  );
}
